<?php

namespace App\Models;

use App\Utils\UrlUtils;
use Illuminate\Database\Eloquent\Model;

class Url extends Model
{

    public $timestamps = false;

    protected $fillable = [
        'url',
        'movie_id',
        'episode_id',
        'downloaded',
        'invalid',
        'last_validated_date',
        'auto_valid',
        'host',
        'quality',
        'auto_download',
        'package_name',
        'auto_download_status',
        'status',
        'package_uuid',
    ];

    protected $casts = [
        'downloaded' => 'boolean',
        'invalid' => 'boolean',
        'auto_valid' => 'boolean',
        'auto_download' => 'boolean',

    ];

    public function episode(){
        return $this->belongsTo(Episode::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->last_validated_date = '2023-10-10';

            if(!isset($model->auto_valid)){
                $model->auto_valid = false;
            }
            if(!isset($model->downloaded)){
                $model->downloaded = false;
            }
            if(!isset($model->invalid)){
                $model->invalid = false;
            }
            if(!isset($model->movie_id)){
                $model->movie_id = 0;
            }
            if(!isset($model->episode_id)){
                $model->episode_id = 0;
            }


            if(strlen($model->url) > 0){
                $model->host = parse_url($model->url)['host'];
                $model->quality = UrlUtils::getQualityFromUrl($model->url);
            }
        });
        static::updating(function ($model){
            if(strlen($model->url) > 0){
                $model->host = parse_url($model->url)['host'];
                $model->quality = UrlUtils::getQualityFromUrl($model->url);
            }
        });
    }


}
