name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dbdocs
        run: sudo npm install -g dbdocs
      - name: Check dbdocs
        run: dbdocs
      # concat recursive all dbml files into _output.dbml
      - name: Concat dbml files
        run: |
          cat $(find . -name "*.dbml") > _output.dbml
      - name: echo dbml files
        run: |
          cat _output.dbml
      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./_output.dbml
